# Bevbox docker-compose.yaml
version: '3.7'

services:

  postgresql:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - "postgres:/var/lib/postgresql/data"
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_ENV: "prod"
      SECRET_KEY: ${SECRET_KEY}
      BOT_TOKEN: ${BOT_TOKEN}
      CHANNEL_ID: ${CHANNEL_ID}
      EMAIL_RECIPIENT: ${EMAIL_RECIPIENT}
      MAILGUN_API_KEY: ${MAILGUN_API_KEY}
      MAILGUN_DOMAIN_NAME: ${MAILGUN_DOMAIN_NAME}
      SQLALCHEMY_DATABASE_URI: ${SQLALCHEMY_DATABASE_URI}
      CREDIT_CARD: ${CREDIT_CARD}
    depends_on:
      - postgresql
    restart: always

  letsencrypt:
    image: linuxserver/letsencrypt
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=bevbox.com.ua
      - VALIDATION=http
      - EMAIL=vladyslav.krylasov@gmail.com
      - DHLEVEL=4096
    volumes:
      - "letsencrypt:/config"
      - "./conf/bevbox.conf:/config/nginx/site-confs/default"
      - "./static:/app/static"
    ports:
      - 443:443
      - 80:80
    depends_on:
      - backend
    restart: always

volumes:
  postgres:
    driver: local
  letsencrypt:
    driver: local
