# Bevbox docker-compose.yaml
version: '3.7'

services:

  postgresql:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - "postgres:/var/lib/postgresql/data"
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_ENV: "prod"
      SECRET_KEY: ${SECRET_KEY}
      BOT_TOKEN: ${BOT_TOKEN}
      CHANNEL_ID: ${CHANNEL_ID}
      EMAIL_RECIPIENT: ${EMAIL_RECIPIENT}
      MAILGUN_API_KEY: ${MAILGUN_API_KEY}
      MAILGUN_DOMAIN_NAME: ${MAILGUN_DOMAIN_NAME}
      SQLALCHEMY_DATABASE_URI: ${SQLALCHEMY_DATABASE_URI}
    depends_on:
      - postgresql
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - "./conf/bevbox.conf:/etc/nginx/conf.d/default.conf"
      - "./static:/app/static"
      - "${HOME}/.config/docker-volumes/etc/letsencrypt:/etc/letsencrypt"
    depends_on:
      - backend
    restart: always

volumes:
  postgres:
    driver: local
