"""Add additions field.

Revision ID: 2912ddbc629c
Revises: 9a4fded78143
Create Date: 2019-02-24 11:53:10.145113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2912ddbc629c'
down_revision = '9a4fded78143'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('additions', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'additions')
    # ### end Alembic commands ###
