"""Drop callback field.

Revision ID: 47ef3cc17c16
Revises: d1fd085e779d
Create Date: 2019-06-18 20:40:01.818777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47ef3cc17c16'
down_revision = 'd1fd085e779d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'callback')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('callback', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
