"""Update order table fields.

Revision ID: d1fd085e779d
Revises: 2912ddbc629c
Create Date: 2019-06-09 20:19:41.917410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1fd085e779d'
down_revision = '2912ddbc629c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('callback', sa.Boolean(), nullable=True))
    op.add_column('order', sa.Column('guillotine', sa.Boolean(), nullable=True))
    op.add_column('order', sa.Column('matches', sa.Boolean(), nullable=True))
    op.add_column('order', sa.Column('payment_option', sa.String(length=2), nullable=True))
    op.add_column('order', sa.Column('stones', sa.Boolean(), nullable=True))
    op.drop_column('order', 'additions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('additions', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('order', 'stones')
    op.drop_column('order', 'payment_option')
    op.drop_column('order', 'matches')
    op.drop_column('order', 'guillotine')
    op.drop_column('order', 'callback')
    # ### end Alembic commands ###
