"""Add cigar field.

Revision ID: ee466690791e
Revises: 47ef3cc17c16
Create Date: 2019-06-18 21:43:04.593177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee466690791e'
down_revision = '47ef3cc17c16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('cigar', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'cigar')
    # ### end Alembic commands ###
